name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5
        
      - name: Change wrapper permissions
        run: chmod +x ./gradlew
        
      - name: Build with Gradle Wrapper
        run: ./gradlew build

      - name: Upload # 上传
        uses: softprops/action-gh-release@v2 # 使用第三方actions 上传
        if: startsWith(github.ref, 'refs/tags/') # 仅在tag时上传
        with:
          files: build/libs/mdimg-*.jar # 上传的文件
